// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/francoganga/go_reno2/ent/passwordtoken"
	"github.com/francoganga/go_reno2/ent/schema"
	"github.com/francoganga/go_reno2/ent/tramite"
	"github.com/francoganga/go_reno2/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	passwordtokenFields := schema.PasswordToken{}.Fields()
	_ = passwordtokenFields
	// passwordtokenDescHash is the schema descriptor for hash field.
	passwordtokenDescHash := passwordtokenFields[0].Descriptor()
	// passwordtoken.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	passwordtoken.HashValidator = passwordtokenDescHash.Validators[0].(func(string) error)
	// passwordtokenDescCreatedAt is the schema descriptor for created_at field.
	passwordtokenDescCreatedAt := passwordtokenFields[1].Descriptor()
	// passwordtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	passwordtoken.DefaultCreatedAt = passwordtokenDescCreatedAt.Default.(func() time.Time)
	tramiteFields := schema.Tramite{}.Fields()
	_ = tramiteFields
	// tramiteDescCreatedAt is the schema descriptor for created_at field.
	tramiteDescCreatedAt := tramiteFields[3].Descriptor()
	// tramite.DefaultCreatedAt holds the default value on creation for the created_at field.
	tramite.DefaultCreatedAt = tramiteDescCreatedAt.Default.(func() time.Time)
	// tramiteDescUpdatedAt is the schema descriptor for updated_at field.
	tramiteDescUpdatedAt := tramiteFields[4].Descriptor()
	// tramite.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tramite.DefaultUpdatedAt = tramiteDescUpdatedAt.Default.(func() time.Time)
	// tramiteDescID is the schema descriptor for id field.
	tramiteDescID := tramiteFields[0].Descriptor()
	// tramite.DefaultID holds the default value on creation for the id field.
	tramite.DefaultID = tramiteDescID.Default.(func() uuid.UUID)
	userHooks := schema.User{}.Hooks()
	user.Hooks[0] = userHooks[0]
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescVerified is the schema descriptor for verified field.
	userDescVerified := userFields[3].Descriptor()
	// user.DefaultVerified holds the default value on creation for the verified field.
	user.DefaultVerified = userDescVerified.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}

const (
	Version = "v0.11.4"                                         // Version of ent codegen.
	Sum     = "h1:grwVY0fp31BZ6oEo3YrXenAuv8VJmEw7F/Bi6WqeH3Q=" // Sum of ent codegen.
)
