// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "tramite_events", Type: field.TypeUUID, Nullable: true},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "events_tramites_events",
				Columns:    []*schema.Column{EventsColumns[3]},
				RefColumns: []*schema.Column{TramitesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ObservacionsColumns holds the columns for the "observacions" table.
	ObservacionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// ObservacionsTable holds the schema information for the "observacions" table.
	ObservacionsTable = &schema.Table{
		Name:       "observacions",
		Columns:    ObservacionsColumns,
		PrimaryKey: []*schema.Column{ObservacionsColumns[0]},
	}
	// PasswordTokensColumns holds the columns for the "password_tokens" table.
	PasswordTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "password_token_user", Type: field.TypeInt},
	}
	// PasswordTokensTable holds the schema information for the "password_tokens" table.
	PasswordTokensTable = &schema.Table{
		Name:       "password_tokens",
		Columns:    PasswordTokensColumns,
		PrimaryKey: []*schema.Column{PasswordTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "password_tokens_users_user",
				Columns:    []*schema.Column{PasswordTokensColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TramitesColumns holds the columns for the "tramites" table.
	TramitesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "ano_presupuestario", Type: field.TypeInt},
		{Name: "link", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "categoria", Type: field.TypeString},
		{Name: "version", Type: field.TypeInt},
		{Name: "user_tramites", Type: field.TypeInt, Nullable: true},
	}
	// TramitesTable holds the schema information for the "tramites" table.
	TramitesTable = &schema.Table{
		Name:       "tramites",
		Columns:    TramitesColumns,
		PrimaryKey: []*schema.Column{TramitesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tramites_users_tramites",
				Columns:    []*schema.Column{TramitesColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EventsTable,
		ObservacionsTable,
		PasswordTokensTable,
		TramitesTable,
		UsersTable,
	}
)

func init() {
	EventsTable.ForeignKeys[0].RefTable = TramitesTable
	PasswordTokensTable.ForeignKeys[0].RefTable = UsersTable
	TramitesTable.ForeignKeys[0].RefTable = UsersTable
}
