// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Observacion is the predicate function for observacion builders.
type Observacion func(*sql.Selector)

// PasswordToken is the predicate function for passwordtoken builders.
type PasswordToken func(*sql.Selector)

// Tramite is the predicate function for tramite builders.
type Tramite func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
